setwd('/Users/chekali1/Dropbox/Work/bispecific_markers_project/scrna')
library(harmony)
library(Seurat)
library(ggplot2)
vital_organs=merge(x=brain_boolean_whole,y=c(heart_boolean_whole,liver_boolean_whole,lung_boolean_whole,kidney_scrna))
head(vital_organs)
#saveRDS(vital_organs,file='vital_organs.rds')
vital_organs=readRDS(file='vital_organs.rds')
table(vital_organs$Organ)

vital_organs

vital_organs[["percent.mt"]] <- PercentageFeatureSet(vital_organs, pattern = "^MT-")
VlnPlot(vital_organs, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 0)
vital_organs <- subset(vital_organs, subset = nFeature_RNA > 0 & percent.mt < 50 )
vital_organs <- NormalizeData(vital_organs, normalization.method = "LogNormalize", scale.factor = 10000)
vital_organs <- FindVariableFeatures(vital_organs, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(vital_organs)
vital_organs <- ScaleData(vital_organs)
vital_organs <- ScaleData(vital_organs)
vital_organs <- FindVariableFeatures(vital_organs)
vital_organs <- RunPCA(vital_organs, features = VariableFeatures(object = vital_organs))
#vital_organs=RunHarmony(vital_organs,c('Organ'))
#print(all_data_seurat[["pca"]], dims = 1:5, nfeatures = 5)
VizDimLoadings(vital_organs, dims = 1:2, reduction = "pca")
#heps <- JackStraw(heps, num.replicate = 100)
#heps <- ScoreJackStraw(heps, dims = 1:50)
vital_organs <- FindNeighbors(vital_organs, dims = 1:30,verbose=TRUE)

set.seed(123)
vital_organs <- FindClusters(vital_organs, resolution = 0.8)
head(Idents(vital_organs), 5)
vital_organs <- RunUMAP(vital_organs, dims = 1:30)
ElbowPlot(vital_organs,reduction='umap')

favorable_markers=c('GPC3','PIGY','PVLAP','CD34','MUC13','TMEM150B')

VlnPlot(vital_organs, features = favorable_markers,combine=F,group.by = 'cell.type')
VlnPlot(vital_organs, features = favorable_markers,combine=T,group.by = 'Organ',stack=T)
VlnPlot(vital_organs, features = favorable_markers,combine=F,group.by = 'Level.1')
VlnPlot(vital_organs, features = favorable_markers,combine=F,group.by = 'Level.2')

RidgePlot(vital_organs, features = favorable_markers,group.by = 'Organ')
DoHeatmap(vital_organs, features = favorable_markers, size = 3)

pdf('Vital_organs.pdf')
DimPlot(vital_organs, reduction = "umap",label=T,group.by = 'cell.type')+ggtitle('UMAP of vital organs by Level 3 aggregation')
DimPlot(vital_organs, reduction = "umap",label=T,group.by = 'Organ')+ggtitle('UMAP of vital organs by Organ')
DimPlot(vital_organs, reduction = "umap",label=T,group.by = 'Level.1')+ggtitle('UMAP of vital organs by Level 1 aggregation')
DimPlot(vital_organs, reduction = "umap",label=T,group.by = 'Level.2')+ggtitle('UMAP of vital organs by Level 2 aggregation')

DimPlot(vital_organs, reduction = "harmony",label=T,group.by = 'cell.type')+ggtitle('Harmony of vital organs by Level 3 aggregation')
DimPlot(vital_organs, reduction = "harmony",label=T,group.by = 'Organ')+ggtitle('Harmony of vital organs by Organ')
DimPlot(vital_organs, reduction = "harmony",label=T,group.by = 'Level.1')+ggtitle('Harmony of vital organs by Level 1 aggregation')
DimPlot(vital_organs, reduction = "harmony",label=T,group.by = 'Level.2')+ggtitle('Harmony of vital organs by Level 2 aggregation')
dev.off()
